// AUTO-GENERATED by tinyml_model/train_classifier.py -- DO NOT EDIT BY HAND.
// Regenerate with: python3 tinyml_model/train_classifier.py
//
// Trained 2026-08-05T11:53:23.606874 on 900 rows of
// tinyml_model/dataset.csv (data_source=synthetic_physics only).
//
// Held-out accuracy on a 20% stratified split: 70.6%
// This is SYNTHETIC-SET separability, not real-concrete accuracy -- see
// AUDIT.md and dataset_generator.py. The deployed model below is refit on
// 100% of the data after that honest number was recorded.
//
// Architecture: 7 -> 12 (ReLU) -> 3 (softmax)
// Float32, NOT quantized -- see train_classifier.py module docstring for why.

#pragma once

static const int MODEL_N_FEATURES = 7;
static const int MODEL_N_HIDDEN = 12;
static const int MODEL_N_CLASSES = 3;

// Feature order the model expects -- MUST match FEATURE_COLUMNS in
// tinyml_model/dataset_generator.py and how the firmware assembles the vector
// in runMeasurementCycle(). Getting this order wrong compiles fine and
// produces confident, silently-wrong classifications.
// ['moisture_mv', 'temperature_c', 'penetration_force_n', 'vib_rms_g', 'vib_dominant_hz', 'vib_spectral_entropy', 'vib_damping_ratio']

// Class order is alphabetical (sklearn's default): ['GOOD', 'MARGINAL', 'REJECT']
static const char* const MODEL_CLASS_NAMES[3] = {
  "GOOD", "MARGINAL", "REJECT"
};

// StandardScaler: (x - mean) / scale, applied per-feature before layer 1.
static const float MODEL_FEATURE_MEAN[7] = {2386.5581f, 29.804167f, 0.72709912f, 0.34668058f, 36.291245f, 0.49857992f, 0.078808263f};
static const float MODEL_FEATURE_SCALE[7] = {87.418777f, 5.1659021f, 0.1917575f, 0.098037221f, 4.7993641f, 0.10021858f, 0.02532433f};

// Layer 1: hidden = relu(x_scaled @ W1 + b1)
static const float MODEL_W1[7][12] = {0.15696095f, -0.41339529f, 0.31124133f, 0.58429581f, 0.48572797f, -0.0040120501f, 0.22720613f, 0.41436154f, 0.11902581f, 0.040042985f, -0.35382387f, -0.12694623f, -0.36835754f, 0.37594697f, 0.016680831f, 0.099888161f, -0.21532965f, -0.16628855f, -0.50227284f, -0.23681918f, 0.56435746f, -0.2019268f, -0.34175783f, 0.30158511f, -0.728948f, -0.71115685f, 0.040303513f, 0.57020903f, -0.66414374f, 0.42637235f, 0.21766527f, -0.32094061f, 0.3021251f, -0.10592722f, -0.032879133f, 0.34441665f, -0.6874848f, -0.45452523f, 0.14440313f, -0.015639946f, -0.24194753f, 0.38444912f, 0.34233192f, -0.26834559f, 0.11614081f, -0.33529833f, -0.13670287f, 0.028080152f, 0.13161643f, -0.6671173f, 0.11030364f, 0.20237166f, -0.39867038f, -0.26784146f, -0.3104248f, -0.35756138f, 0.58596116f, 0.12459172f, -0.13121556f, 0.0508807f, 0.18904454f, -0.31791168f, 0.34120131f, -0.24451017f, -0.36400685f, -0.43733615f, 0.034802228f, 0.14114387f, 0.39294073f, 0.54496884f, -0.076608442f, -0.57692987f, 0.56318361f, -0.033204183f, -0.24566813f, 0.24586512f, -0.37107098f, -0.44869602f, 0.1907807f, -0.016050627f, 0.39471483f, 0.10283504f, -0.49230719f, 0.2069038f};
static const float MODEL_B1[12] = {-0.40008345f, -0.27180386f, -0.20343068f, -0.058118116f, 0.34313515f, -0.35979724f, 0.41018772f, 0.43513027f, -0.39010063f, -0.5564822f, 0.71413183f, -0.25813159f};

// Layer 2: logits = hidden @ W2 + b2  (softmax applied in the inference code)
static const float MODEL_W2[12][3] = {-0.70118111f, -0.29763445f, 0.32193613f, -0.18330258f, 0.42822543f, 0.64674044f, -0.21098578f, -0.24236156f, 0.33641469f, -0.44555786f, 0.3381846f, -0.49988595f, -0.34927955f, -0.4272086f, 0.21569856f, -0.67970419f, -0.298581f, -0.35311326f, -0.20804539f, -0.43945265f, -0.47080952f, 0.17448269f, 0.45741907f, -0.42734244f, -0.061673984f, 0.42326066f, 0.2414542f, -0.201978f, -0.67044014f, 0.49211365f, 0.42639562f, -0.32821476f, -0.65421528f, 0.2341437f, 0.19375426f, -0.14182986f};
static const float MODEL_B2[3] = {-0.31371215f, -0.35706979f, -0.11622129f};
