#pragma once
#include <Arduino.h>

// On-device classifier: 7 features -> 12 hidden (ReLU) -> 3 classes (softmax).
//
// Weights come from model_weights.h, auto-generated by
// tinyml_model/train_classifier.py. See that script's docstring for why this is
// a hand-written float32 forward pass rather than TFLite Micro / Edge Impulse.
//
// The forward pass is verified against sklearn's own predict_proba() output on
// held-out rows by tools/hosttest/ -- a transposed weight matrix or a wrong
// activation would still compile and still produce confident-looking numbers,
// so "it builds" is not evidence it is correct.

struct Inference {
  int classIndex = -1;
  float confidence = 0.0f;               // max softmax probability
  float probabilities[3] = {0, 0, 0};    // indexed by MODEL_CLASS_NAMES order
  bool valid = false;
};

// features[] must be in MODEL_FEATURE_ORDER (see model_weights.h):
//   moisture_mv, temperature_c, penetration_force_n,
//   vib_rms_g, vib_dominant_hz, vib_spectral_entropy, vib_damping_ratio
//
// Returns valid=false if any feature is NaN, rather than propagating NaN
// through the network and emitting a garbage class. A missing sensor must
// produce "no answer", never a confident wrong answer.
Inference runInference(const float* features, int nFeatures);

const char* inferenceClassName(int classIndex);
