// AUTO-GENERATED by tinyml_model/train_classifier.py -- DO NOT EDIT.
// Held-out feature vectors + the class the trained model predicts for
// each, so the on-device self-test always matches the deployed weights.
#pragma once
static const int SELFTEST_N = 3;
static const float SELFTEST_INPUTS[3][7] = {
  {2266.1f, 23.125f, 0.9466f, 0.42642f, 39.683f, 0.57685f, 0.08822f},
  {2495.8f, 32.0f, 0.9019f, 0.47322f, 43.051f, 0.46293f, 0.05291f},
  {2150.8f, 36.8125f, 0.3458f, 0.17117f, 25.905f, 0.74706f, 0.11645f},
};
static const char* const SELFTEST_EXPECTED[3] = {
  "GOOD", "MARGINAL", "REJECT"
};
